Backup1/galante.se/Controllers/LaundryRoomController.cs
using Elmah;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace galante.se.Controllers
{
    public class LaundryRoomController : BaseController
    {
        //
        // GET: /LaundryRoom/
        //public CustomModelBinderAttribute

        public ActionResult Index()
        {
            ErrorSignal.FromCurrentContext().Raise(new NotSupportedException());
            return View();
        }

        [HttpPost]
        public FileContentResult Download(FormCollection formCollection)
        {
            //FileInfo fileInfo = new FileInfo(System.Web.HttpContext.Current.Server.MapPath("~/Documents/EM-tipset 2012 Mall.xlsx"));
            FileInfo fileInfo = new FileInfo(System.Web.HttpContext.Current.Server.MapPath("~/Documents/laundry-room/schema-template.xlsx"));

            using (ExcelPackage p = new ExcelPackage())
            {
                ////Kontrollerar om filen finns
                //if (System.IO.File.Exists(fileInfo.FullName))
                //{
                //    //Skapar filen genom att kopiera mallen
                //    FileInfo templateFileInfo = new FileInfo(System.Web.HttpContext.Current.Server.MapPath("~/Documents/EM-tipset 2012 Mall.xlsx"));
                //    System.IO.File.Copy(templateFileInfo.FullName, fileInfo.FullName);
                //}

                FileStream fileStream = new FileStream(fileInfo.FullName, FileMode.Open);

                p.Load(fileStream);
                fileStream.Close();

                //Create a sheet
                ExcelWorksheet ws = p.Workbook.Worksheets["Blad1"];

                //Manipulerar formuläret
                DateTime dummyDate;
                //DateTime? fromDate = DateTime.TryParse(formCollection["fromDate"], out dummyDate) ? (DateTime?)dummyDate : null;
                DateTime? fromDate = DateTime.TryParse(formCollection["fromDate"], out dummyDate) ? 
                    (DateTime?)DateTime.Parse(formCollection["fromDate"]) : null;
                DateTime? toDate = DateTime.TryParse(formCollection["toDate"], out dummyDate) ? 
                    (DateTime?)DateTime.Parse(formCollection["toDate"]) : null;

                ws.Cells[1, 3].Value = FirstCharToUpper(fromDate.Value.ToString("MMMM", this.CurrentCulture));

                int daysInMonth = DateTime.DaysInMonth(fromDate.Value.Year, fromDate.Value.Month);
                int rowNumber;
                DateTime schemaStartDate = new DateTime(fromDate.Value.Year, fromDate.Value.Month, 1);
                for (int i = 1; i <= 31; i++)
			    {
                    if (i <= daysInMonth)
                    {
                        rowNumber = i + 2;
                        ws.Cells[rowNumber, 1].Value = schemaStartDate.AddDays(i - 1).ToString("dddd", this.CurrentCulture);
                        ////Sätter bakgrundsfärg
                        ////http://stackoverflow.com/questions/1617049/calculate-the-number-of-business-days-between-two-dates
                        //ws.Cells[rowNumber, 1].Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
                        //ws.Cells[rowNumber, 1].Style.Fill.BackgroundColor.SetColor(Color.Aquamarine);
                    }
                    else
                    {
                        //Tar bort raden om dagen inte finns i månaden
                        ws.DeleteRow(daysInMonth + 3, 1);
                    }
			    }

                //for (int i = daysInMonth; i <= 31; i++)
                //{
                //    //Tar bort raden om dagen inte finns i månaden
                //    ws.DeleteRow(rowNumber, 1);
                //}

                //Generate A File with Random name
                Byte[] bin = p.GetAsByteArray();
                //System.IO.File.WriteAllBytes(fileInfo.FullName, bin);

                return File(bin, "application/octet-stream", "schema.xlsx");
            }
        }

        //
        // GET: /LaundryRoom/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /LaundryRoom/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /LaundryRoom/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /LaundryRoom/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /LaundryRoom/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /LaundryRoom/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /LaundryRoom/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        private static string FirstCharToUpper(string input)
        {
            if (String.IsNullOrEmpty(input))
                throw new ArgumentException("ARGH!");
            return input.First().ToString().ToUpper() + String.Join("", input.Skip(1));
        }
    }
}

Backup1/galante.se/Controllers/WorldCup2014Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace galante.se.Controllers
{
    public class WorldCup2014Controller : Controller
    {
        //
        // GET: /WorldCup2014/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Backup1/galante.se/Views/Shared/Layout/_Layout_Galante.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    @*<title>Tvättstugeschema</title>*@
    <title>@ViewBag.Title</title>
    @*Css:er*@
    @{ Html.RenderPartial("LayoutPartials/_Css"); }
    @RenderSection("Header", required: false)
</head>
<body>
    <div class="container">

        @*Header*@
        <header>

            @*navbar*@
            <div class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                    &nbsp;
                </div>
                @*menu*@
                <div class="navbar-inner">
                    <div class="container">
                        <div class="row">
                            <div class="span6"><span class="logo">Jan Lundholm</span></div>
                            <div class="span6">
                                <nav class="pull-right">
                                    @Html.ActionLink("Hem", "index", "Home")
                                    @*<a href="/">Bort</a>
                                    <a href="/">Hit</a>
                                    <a href="/">Dit</a>*@
                                    @Html.ActionLink("Brazil 2014", "index", "WorldCup2014")
                                    @Html.ActionLink("Tvättstuga", "index", "LaundryRoom")
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Gradient layer -->
                <div class="navbar-inner gradient">
                    <div class="gradient">
                        &nbsp;
                    </div>
                </div>                   
            </div>
        </header>

        @*Content*@
        <div class="row">
            <div class="span12">
                @RenderBody()
            </div>
        </div>

        @*Footer*@
        <footer>
            <div class="row">
                <div class="span12">&nbsp;</div>
            </div>
        </footer>
    </div>

    <!-- /container -->

    @*Javascript*@
    @{ Html.RenderPartial("LayoutPartials/_Javascript"); }
    @RenderSection("Footer", required: false)
</body>
</html>

Backup1/galante.se/Views/Shared/Layout/_Layout_Galante_Bootstrap.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Tvättstugeschema</title>
    <!-- Bootstrap -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/Content/bootstrap-datepicker/css/datepicker.css" rel="stylesheet" media="screen">
    @*Eget ramverk*@
    <link href="/Content/bootstrap/css/framework.css" rel="stylesheet" media="screen">
    @*Helt egna css-er*@
    <link href="/Content/base.css" rel="stylesheet" media="screen">
</head>
<body style="padding:40px">
    <div class="container">


        <div class="row">
            <div class="span12">
                <div class="navbar navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container">
                            <a class="brand" href="#">Jan Lundholm</a>
                            <ul class="nav">
                                <li class="active">@Html.ActionLink("Hem", "index", "Home")</li>
                                <li><a href="#">Bort</a></li>
                                <li><a href="#">Hit</a></li>
                                <li><a href="#">Dit</a></li>
                                <li>@Html.ActionLink("Tvättstuga", "index", "LaundryRoom")</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>



        @*Header*@
        <div>
   
            @*breadcrumb*@
             <div class="row visible-phone">
                <div class="span12">
                    <ul class="breadcrumb">
                      <li><a href="#">Home</a> <span class="divider">/</span></li>
                      <li><a href="#">Library</a> <span class="divider">/</span></li>
                      <li class="active">Data</li>
                    </ul>
                </div>
            </div>

        </div>

        @*Content*@
        <div class="row">
            <div class="span12">
                @RenderBody()
            </div>
        </div>

        @*Footer*@
        <div class="row">
            <div class="span12" style="background-color:gray;"></div>
        </div>
        
    </div>
    <!-- /container -->

    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="/Content/bootstrap/js/bootstrap.min.js"></script>
    <script src="/Content/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script>$('.date').datepicker()</script>
</body>
</html>